data:extend({
	{
		type = "recipe",
		name = "fermented-fish",
		category = "decomposition",
		additional_categories = { "organic" },
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "coconut-meat", amount = 5 },
			{ type = "item", name = "raw-fish", amount = 10 },
			{ type = "item", name = "fermentation-bacteria", amount = 5 },
		},
		results = {
			--{ type = "item", name = "fermented-fish", amount = 5 },
			{ type = "item", name = "fermented-fish", amount = 10 },
		},
		crafting_machine_tint = {
			primary = { r = 0.6, g = 0.77, b = 0.82, a = 1.000 },
			secondary = { r = 0.78, g = 0.82, b = 0.35, a = 1.000 },
			tertiary = { r = 0.6, g = 0.77, b = 0.82, a = 1.000 },
			quaternary = { r = 0.78, g = 0.82, b = 0.35, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "wood-spoiling",
		icon = "__pelagos__/graphics/rotting-wood.png",
		category = "decomposition",
		additional_categories = { "organic" },
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "wood", amount = 5 },
		},
		results = {
			{ type = "item", name = "spoilage", amount = 40 },
		},
		crafting_machine_tint = {
			primary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			secondary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
			tertiary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			quaternary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-husk-spoiling",
		icon = "__pelagos__/graphics/coconut-husk-spoiling.png",
		category = "decomposition",
		additional_categories = { "organic" },
		subgroup = "agriculture-products",
		order = "a[seeds]-c[wood-spoiling]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "coconut-husk", amount = 5 },
		},
		results = {
			{ type = "item", name = "spoilage", amount = 20 },
		},
		crafting_machine_tint = {
			primary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			secondary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
			tertiary = { r = 0.27, g = 0.27, b = 0.08, a = 1.000 },
			quaternary = { r = 0.37, g = 0.37, b = 0.18, a = 1.000 },
		},
	},
})
