data:extend({
	{
		type = "recipe",
		name = "pelagos-rocket-part",
		icons = {
			{ icon = "__base__/graphics/icons/rocket-part.png", icon_size = 64 },
			{ icon = "__pelagos__/graphics/planet/pelagos64.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
		},
		energy_required = 3,
		enabled = false,
		hide_from_player_crafting = true,
		auto_recycle = false,
		category = "rocket-building",
		ingredients = {
			{ type = "item", name = "processing-unit", amount = 1 },
			{ type = "item", name = "titanium-plate", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 100 },
		},
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		results = { { type = "item", name = "rocket-part", amount = 1 } },
		allow_productivity = true,
	},
})
data:extend({
	{
		type = "recipe",
		name = "nutrients-from-coconut-meat",
		icon = "__pelagos__/graphics/nutrients-from-coconut-meat.png",
		category = "organic",
		subgroup = "agriculture-processes",
		enabled = false,
		allow_productivity = true,
		order = "c[nutrients]-d[nutrients-from-coconut-meat]",
		energy_required = 4,
		ingredients = { { type = "item", name = "coconut-meat", amount = 2 } },
		--results = { { type = "item", name = "nutrients", amount = 8 } },
		results = { { type = "item", name = "nutrients", amount = 10 } },
		crafting_machine_tint = {
			primary = { r = 1.000, g = 1.000, b = 0.900, a = 1.000 },
			secondary = { r = 0.900, g = 0.900, b = 0.800, a = 1.000 },
			tertiary = { r = 1.000, g = 1.000, b = 0.900, a = 1.000 },
			quaternary = { r = 0.900, g = 0.900, b = 0.800, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-processing",
		icon = "__pelagos__/graphics/coconut-processing.png",
		category = "organic-or-hand-crafting",
		subgroup = "agriculture-processes",
		order = "a[seeds]-a[coconut-processing]",
		enabled = false,
		allow_productivity = true,
		energy_required = 1,
		ingredients = { { type = "item", name = "coconut", amount = 1 } },
		results = {
			{ type = "item", name = "coconut-seed", amount = 1, probability = 0.09 },
			{ type = "item", name = "coconut-meat", amount = 2 },
			{ type = "item", name = "coconut-husk", amount = 2 },
		},
		crafting_machine_tint = {
			primary = { r = 0.860, g = 0.770, b = 0.590, a = 1.000 },
			secondary = { r = 0.720, g = 0.520, b = 0.260, a = 1.000 },
			tertiary = { r = 0.860, g = 0.770, b = 0.590, a = 1.000 },
			quaternary = { r = 0.720, g = 0.520, b = 0.260, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-oil",
		category = "organic-or-chemistry",
		additional_categories = { "cryogenics" },
		subgroup = "fluid-recipes",
		order = "a[fluid]-b[coconut-oil]",
		auto_recycle = false,
		energy_required = 6,
		ingredients = {
			{ type = "item", name = "coconut-meat", amount = 10 },
		},
		results = { { type = "fluid", name = "coconut-oil", amount = 10 } },
		allow_productivity = true,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 1.000, g = 0.940, b = 0.620, a = 1.000 },
			secondary = { r = 0.900, g = 0.780, b = 0.500, a = 1.000 },
			tertiary = { r = 1.000, g = 0.940, b = 0.620, a = 1.000 },
			quaternary = { r = 0.900, g = 0.780, b = 0.500, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "coconut-sealant",
		category = "organic-or-assembling",
		subgroup = "agriculture-processes",
		order = "a[advanced-intermediats]-b[coconut-sealant]",
		auto_recycle = false,
		energy_required = 8,
		ingredients = {
			{ type = "fluid", name = "coconut-oil", amount = 10 },
			{ type = "item", name = "coconut-husk", amount = 5 },
		},
		results = { { type = "item", name = "coconut-sealant", amount = 1 } },
		allow_productivity = true,
		enabled = false,
		crafting_machine_tint = {
			primary = { r = 0.850, g = 0.650, b = 0.450, a = 1.000 },
			secondary = { r = 0.600, g = 0.450, b = 0.300, a = 1.000 },
			tertiary = { r = 0.850, g = 0.650, b = 0.450, a = 1.000 },
			quaternary = { r = 0.600, g = 0.450, b = 0.300, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "pelagos-biodiesel-tree",
		category = "oil-processing",
		subgroup = "fluid-recipes",
		additional_categories = { "organic" },
		icons = {
			{ icon = "__pelagos__/graphics/biodiesel.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/tree-seed.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
		},
		surface_conditions = {},
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "tree-seed", amount = 5 },
			{ type = "fluid", name = "steam", amount = 50 },
		},
		results = {
			{ type = "fluid", name = "biodiesel", amount = 50 },
		},
		crafting_machine_tint = {
			primary = { r = 0.54, g = 0.45, b = 0.05 },
			secondary = { r = 0.64, g = 0.55, b = 0.15 },
			tertiary = { r = 0.54, g = 0.45, b = 0.05 },
			quaternary = { r = 0.64, g = 0.55, b = 0.15 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "pelagos-biodiesel-spoilage",
		category = "organic",
		icons = {
			{ icon = "__pelagos__/graphics/biodiesel.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/spoilage.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
		},
		subgroup = "fluid-recipes",
		surface_conditions = {},
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "spoilage", amount = 40 },
			{ type = "fluid", name = "lubricant", amount = 10 },
		},
		results = {
			{ type = "fluid", name = "biodiesel", amount = 20 },
		},
		crafting_machine_tint = {
			primary = { r = 0.54, g = 0.45, b = 0.05 },
			secondary = { r = 0.64, g = 0.55, b = 0.15 },
			tertiary = { r = 0.54, g = 0.45, b = 0.05 },
			quaternary = { r = 0.64, g = 0.55, b = 0.15 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "pelagos-biodiesel-solid-fuel",
		icons = {
			{ icon = "__base__/graphics/icons/solid-fuel.png", icon_size = 64 },
			{ icon = "__pelagos__/graphics/biodiesel.png", icon_size = 64, scale = 0.3, shift = { -8, -8 } },
		},
		energy_required = 2,
		enabled = false,
		category = "organic-or-chemistry",
		auto_recycle = false,
		subgroup = "fluid-recipes",
		order = "b[fluid-chemistry]-b[solid-fuel-from-biodiesel]",
		ingredients = {
			{ type = "fluid", name = "biodiesel", amount = 15 },
		},
		results = { { type = "item", name = "solid-fuel", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.54, g = 0.45, b = 0.05 },
			secondary = { r = 0.64, g = 0.55, b = 0.15 },
			tertiary = { r = 0.54, g = 0.45, b = 0.05 },
			quaternary = { r = 0.64, g = 0.55, b = 0.15 },
		},
	},
	{
		type = "recipe",
		name = "ethanol",
		category = "organic",
		subgroup = "fluid-recipes",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "decomposition-bacteria", amount = 5 },
			{ type = "item", name = "nutrients", amount = 20 },
			{ type = "fluid", name = "water", amount = 100 },
			{ type = "item", name = "activated-carbon", amount = 3 },
		},
		results = {
			{ type = "fluid", name = "ethanol", amount = 120 },
		},
		crafting_machine_tint = {
			primary = { r = 0.68, g = 0.83, b = 0.9, a = 1.000 },
			secondary = { r = 0.78, g = 0.93, b = 1.0, a = 1.000 },
			tertiary = { r = 0.68, g = 0.83, b = 0.9, a = 1.000 },
			quaternary = { r = 0.78, g = 0.93, b = 1.0, a = 1.000 },
		},
		show_amount_in_title = false,
	},
	{
		type = "recipe",
		name = "degradation-module",
		enabled = false,
		auto_recycle = false,
		category = "decomposition",
		additional_categories = { "electromagnetics" },
		ingredients = {
			{ type = "item", name = "quality-module", amount = 1 },
			{ type = "item", name = "decomposition-bacteria", amount = 1 },
		},
		energy_required = 15,
		results = { { type = "item", name = "degradation-module", amount = 1 } },
	},
	{
		type = "recipe",
		name = "degradation-module-2",
		enabled = false,
		auto_recycle = false,
		category = "decomposition",
		additional_categories = { "electromagnetics" },
		ingredients = {
			{ type = "item", name = "quality-module-2", amount = 1 },
			{ type = "item", name = "degradation-module", amount = 4 },
			{ type = "item", name = "decomposition-bacteria", amount = 3 },
		},
		energy_required = 30,
		results = { { type = "item", name = "degradation-module-2", amount = 1 } },
	},
	{
		type = "recipe",
		name = "degradation-module-3",
		enabled = false,
		auto_recycle = false,
		category = "decomposition",
		additional_categories = { "electromagnetics" },
		ingredients = {
			{ type = "item", name = "quality-module-3", amount = 1 },
			{ type = "item", name = "degradation-module-2", amount = 4 },
			{ type = "item", name = "decomposition-bacteria", amount = 5 },
		},
		energy_required = 60,
		results = { { type = "item", name = "degradation-module-3", amount = 1 } },
	},
	{
		type = "recipe",
		name = "lighthouse",
		category = "advanced-crafting",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "pipe", amount = 10 },
			{ type = "item", name = "iron-plate", amount = 20 },
			{ type = "item", name = "concrete", amount = 200 },
			{ type = "item", name = "coconut-sealant", amount = 10 },
		},
		energy_required = 10,
		results = { { type = "item", name = "lighthouse", amount = 1 } },
	},
	{

		type = "recipe",
		name = "crane-stack-diesel-inserter",
		enabled = false,
		ingredients = {
			{ type = "item", name = "engine-unit", amount = 5 },
			{ type = "item", name = "coconut-sealant", amount = 6 },
			{ type = "item", name = "stack-inserter", amount = 1 },
			{ type = "item", name = "crane-bulk-diesel-inserter", amount = 1 },
			{ type = "item", name = "titanium-plate", amount = 10 },
		},
		results = { { type = "item", name = "crane-stack-diesel-inserter", amount = 1 } },
	},
	{
		type = "recipe",
		name = "diesel-agricultural-tower",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "coconut-sealant", amount = 2 },
			{ type = "item", name = "steel-plate", amount = 10 },
			{ type = "item", name = "engine-unit", amount = 3 },
			{ type = "item", name = "spoilage", amount = 20 },
			{ type = "item", name = "landfill", amount = 1 },
		},
		results = { { type = "item", name = "diesel-agricultural-tower", amount = 1 } },
		enabled = false,
	},
	{
		type = "recipe",
		name = "titanium-dust",
		category = "organic",
		subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 5,
		ingredients = {
			{ type = "fluid", name = "titanium-sludge", amount = 50 },
			{ type = "item", name = "decomposition-bacteria", amount = 1 },
		},
		results = {
			{ type = "item", name = "titanium-dust", amount = 1, probability = 0.25 },
			{ type = "item", name = "spoilage", amount = 8 },
		},
		crafting_machine_tint = {
			primary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			secondary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
			tertiary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			quaternary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
		},
		main_product = "titanium-dust",
	},
	{
		type = "recipe",
		name = "advanced-titanium-plate-from-dust",
		icon = "__pelagos__/graphics/titanium/advanced-titanium-plate-from-dust.png",
		--subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		category = "smelting",
		enabled = false,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-dust", amount = 1 },
			{ type = "item", name = "activated-carbon", amount = 10 },
		},
		results = { { type = "item", name = "titanium-plate", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			secondary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
			tertiary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			quaternary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "titanium-plate-from-dust",
		icon = "__pelagos__/graphics/titanium/titanium-plate-from-dust.png",
		--subgroup = "agriculture-products",
		--order = "a[seeds]-c[]",
		auto_recycle = false,
		category = "smelting",
		enabled = false,
		energy_required = 10,
		ingredients = { { type = "item", name = "titanium-dust", amount = 2 } },
		results = { { type = "item", name = "titanium-plate", amount = 1 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			secondary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
			tertiary = { r = 0.45, g = 0.67, b = 0.72, a = 1.000 },
			quaternary = { r = 0.65, g = 0.87, b = 0.92, a = 1.000 },
		},
	},

	{
		type = "recipe",
		name = "titanium-barrel",
		category = "crafting",
		energy_required = 1,
		subgroup = "intermediate-product",
		enabled = false,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 1 },
		},
		results = { { type = "item", name = "titanium-barrel", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "diesel-dragon",
		enabled = false,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 500 },
			{ type = "item", name = "steel-plate", amount = 1000 },
			{ type = "item", name = "concrete", amount = 1000 },
			{ type = "item", name = "pipe", amount = 300 },
			{ type = "item", name = "processing-unit", amount = 200 },
			{ type = "item", name = "engine-unit", amount = 400 },
		},
		energy_required = 30,
		results = { { type = "item", name = "diesel-dragon", amount = 1 } },
		requester_paste_multiplier = 1,
	},
	{
		type = "recipe",
		name = "titanium-storage-tank",
		enabled = false,
		energy_required = 3,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 10 },
			{ type = "item", name = "storage-tank", amount = 3 },
		},
		results = { { type = "item", name = "titanium-storage-tank", amount = 1 } },
	},
})

data:extend({
	{
		type = "recipe",
		name = "copper-biter-egg",
		category = "captive-spawner-process",
		order = "c[eggs]-a[copper-biter-egg]",
		hide_from_player_crafting = true,
		auto_recycle = false,
		preserve_products_in_machine_output = true,
		energy_required = 10,
		ingredients = {},
		results = {
			{ type = "item", name = "copper-biter-egg", amount = 10 },
		},
		enabled = false,
	},
	{
		type = "recipe",
		name = "copper-plate-from-copper-biter-egg",
		icon = "__pelagos__/graphics/copper-plate.png",
		category = "smelting",
		auto_recycle = false,
		energy_required = 3.2,
		ingredients = { { type = "item", name = "copper-biter-egg", amount = 1 } },
		results = { { type = "item", name = "copper-plate", amount = 1 } },
		allow_productivity = true,
		enabled = false,
	},
	{
		type = "recipe",
		name = "copper-ore-bitter-egg",
		category = "organic",
		subgroup = "agriculture-products",
		order = "a[pelagos]-c[copper-ore-bitter-egg]",
		icon = "__pelagos__/graphics/copper-ore.png",
		auto_recycle = false,
		enabled = false,
		allow_productivity = true,
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "copper-biter-egg", amount = 5 },
			{ type = "item", name = "calcite", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 25 },
		},
		results = {
			{ type = "item", name = "copper-ore", amount = 5 },
		},
		crafting_machine_tint = {
			primary = { r = 0.7, g = 0.3, b = 0.18, a = 1.000 },
			secondary = { r = 0.87, g = 0.41, b = 0.25, a = 1.000 },
			tertiary = { r = 0.7, g = 0.3, b = 0.18, a = 1.000 },
			quaternary = { r = 0.87, g = 0.41, b = 0.25, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "captive-copper-biter-spawner",
		category = "cryogenics",
		energy_required = 10,
		enabled = false,
		reset_freshness_on_craft = true,
		ingredients = {
			{ type = "item", name = "copper-biter-egg", amount = 10 },
			{ type = "item", name = "pelagos-capture-robot-rocket", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 500 },
			{ type = "fluid", name = "fluoroketone-cold", amount = 100 },
		},
		results = { { type = "item", name = "captive-copper-biter-spawner", amount = 1 } },
	},
})
--weapons
data:extend({
	{
		type = "recipe",
		name = "pelagos-capture-robot-rocket",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 3 },
			{ type = "item", name = "fermented-fish", amount = 10 },
			{ type = "item", name = "engine-unit", amount = 5 },
			{ type = "item", name = "plastic-bar", amount = 10 },
		},
		results = { { type = "item", name = "pelagos-capture-robot-rocket", amount = 1 } },
		enabled = false,
		auto_recycle = false,
	},
	{
		type = "recipe",
		name = "corrosive-firearm-magazine",
		energy_required = 1,
		ingredients = {
			{ type = "item", name = "firearm-magazine", amount = 6 },
			{ type = "item", name = "decomposition-bacteria", amount = 1 },
		},
		results = { { type = "item", name = "corrosive-firearm-magazine", amount = 6 } },
		enabled = false,
		auto_recycle = false,
	},
	{
		type = "recipe",
		name = "heavy-gun-turret",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "titanium-plate", amount = 10 },
			{ type = "item", name = "iron-gear-wheel", amount = 20 },
			{ type = "item", name = "steel-plate", amount = 30 },
			{ type = "item", name = "engine-unit", amount = 10 },
			{ type = "item", name = "plastic-bar", amount = 15 },
		},
		results = { { type = "item", name = "heavy-gun-turret", amount = 1 } },
		enabled = false,
		--auto_recycle = false,
	},
})

data:extend({
	{
		type = "recipe",
		name = "nutrients-from-spoilage-methane",
		icons = {
			{ icon = "__pelagos__/graphics/methane.png", icon_size = 64 },
			{ icon = "__space-age__/graphics/icons/nutrients-from-spoilage.png", icon_size = 64 },
		},
		category = "decomposition",
		subgroup = "decomposition-products",
		order = "c[nutrients]-c[nutrients-from-spoilage-methane]",
		enabled = false,
		allow_productivity = true,
		energy_required = 2,
		ingredients = {
			{ type = "item", name = "spoilage", amount = 10 },
			{ type = "fluid", name = "methane", amount = 5 },
		},
		results = { { type = "item", name = "nutrients", amount = 2, percent_spoiled = 0.6 } },
		crafting_machine_tint = {
			primary = { r = 0.8, g = 0.9, b = 1, a = 1.000 },
			secondary = { r = 0.5, g = 0.5, b = 0.8, a = 1.000 },
		},
	},
	{
		type = "recipe",
		name = "pelagos-science-pack",
		category = "decomposition",
		subgroup = "science-pack",
		surface_conditions = {
			{
				property = "pressure",
				min = 1809,
				max = 1809,
			},
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "coconut-sealant", amount = 2 },
			{ type = "item", name = "engine-unit", amount = 1 },
			{ type = "item", name = "decomposition-bacteria", amount = 3 },
			{ type = "item", name = "activated-carbon", amount = 1 },
			{ type = "item", name = "titanium-dust", amount = 1 },
			{ type = "fluid", name = "ethanol", amount = 25 },
		},
		energy_required = 8,
		results = { { type = "item", name = "pelagos-science-pack", amount = 2 } },
		allow_productivity = true,
		crafting_machine_tint = {
			primary = { r = 0.39, g = 0.48, b = 0.26, a = 1.000 },
			secondary = { r = 0.49, g = 0.58, b = 0.36, a = 1.000 },
			tertiary = { r = 0.39, g = 0.48, b = 0.26, a = 1.000 },
			quaternary = { r = 0.49, g = 0.58, b = 0.36, a = 1.000 },
		},
	},
})

if mods["Krastorio2-spaced-out"] then
	local electronic_components = table.deepcopy(data.raw["recipe"]["kr-electronic-components"])
	electronic_components.name = "pelagos-electronic-components"
	electronic_components.icons = {
		{ icon = "__Krastorio2Assets__/icons/items/electronic-components.png", icon_size = 64 },
		{ icon = "__pelagos__/graphics/planet/pelagos64.png", icon_size = 64, scale = 0.25, shift = { 8, 8 } },
	}
	electronic_components.ingredients = {
		{ type = "item", name = "kr-glass", amount = 2 },
		{ type = "item", name = "copper-cable", amount = 4 },
		{ type = "item", name = "coconut-sealant", amount = 2 },
		{ type = "item", name = "plastic-bar", amount = 2 },
	}
	electronic_components.surface_conditions = {
		{
			property = "pressure",
			min = 1809,
			max = 1809,
		},
	}
	data:extend({ electronic_components })
	table.insert(
		data.raw["technology"]["advanced-circuit"].effects,
		{ type = "unlock-recipe", recipe = "pelagos-electronic-components" }
	)
end
